# Dependency graph: flake input name → { deps, hasTests }
#
# deps:     list of workspace input names this repo depends on
#           (only logos-co deps; external deps like go-wallet-sdk are omitted)
# hasTests: whether this repo exposes checks or test packages in its flake
#           Used by `ws test` to skip expensive nix eval for repos without tests.
#
# AUTO-GENERATED by `ws sync-graph`. To update: ws sync-graph
#
# If you add a `checks` output to a repo's flake.nix, re-run this command
# so that `ws test --all` picks it up.
{
  logos-cpp-sdk                  = { deps = []; hasTests = false; };
  logos-module                   = { deps = [ "logos-cpp-sdk" ]; hasTests = true; };
  logos-liblogos                 = { deps = [ "logos-cpp-sdk" "logos-module" "logos-capability-module" "nix-bundle-dir" ]; hasTests = true; };
  logos-capability-module        = { deps = [ "logos-cpp-sdk" "logos-liblogos" ]; hasTests = false; };
  logos-package                  = { deps = [ "logos-liblogos" ]; hasTests = true; };
  logos-module-builder           = { deps = [ "logos-cpp-sdk" "logos-liblogos" ]; hasTests = false; };
  nix-bundle-dir                 = { deps = []; hasTests = false; };
  nix-bundle-lgx                 = { deps = [ "logos-package" "nix-bundle-dir" ]; hasTests = false; };
  logos-app                      = { deps = [ "logos-cpp-sdk" "logos-liblogos" "logos-capability-module" "logos-package" "nix-bundle-dir" "nix-bundle-lgx" "logos-package-manager-module" "logos-package-manager-ui" "logos-webview-app" "counter_qml" "counter" "logos-design-system" ]; hasTests = false; };
  logos-accounts-module          = { deps = [ "logos-cpp-sdk" "logos-liblogos" ]; hasTests = false; };
  logos-accounts-ui              = { deps = [ "logos-cpp-sdk" "logos-liblogos" "logos-capability-module" "nix-bundle-lgx" "logos-accounts-module" "logos-package-manager-module" ]; hasTests = false; };
  logos-chat-module              = { deps = [ "logos-cpp-sdk" "logos-liblogos" "logos-waku-module" ]; hasTests = false; };
  logos-chat-legacy-module       = { deps = [ "logos-cpp-sdk" "logos-liblogos" "logos-waku-module" ]; hasTests = false; };
  logos-chat-tui                 = { deps = [ "logos-liblogos" "logos-capability-module" "logos-chat-module" "logos-waku-module" "logos-rust-sdk" ]; hasTests = false; };
  logos-chat-ui                  = { deps = [ "logos-cpp-sdk" "logos-liblogos" "logos-capability-module" "logos-chat-module" "logos-chat-legacy-module" "logos-waku-module" ]; hasTests = false; };
  logos-chatsdk-module           = { deps = [ "logos-cpp-sdk" "logos-liblogos" ]; hasTests = false; };
  logos-chatsdk-ui               = { deps = [ "logos-cpp-sdk" "logos-liblogos" "logos-capability-module" "logos-chatsdk-module" ]; hasTests = false; };
  logos-irc-module               = { deps = [ "logos-cpp-sdk" "logos-liblogos" "logos-capability-module" "logos-chat-module" "logos-chat-legacy-module" "logos-waku-module" ]; hasTests = false; };
  logos-waku-module              = { deps = [ "logos-cpp-sdk" "logos-liblogos" ]; hasTests = false; };
  logos-waku-ui                  = { deps = [ "logos-cpp-sdk" "logos-liblogos" "logos-capability-module" "logos-waku-module" ]; hasTests = false; };
  logos-package-manager-module   = { deps = [ "logos-cpp-sdk" "logos-liblogos" "logos-package" "nix-bundle-dir" ]; hasTests = false; };
  logos-package-manager-ui       = { deps = [ "logos-cpp-sdk" "logos-liblogos" "logos-capability-module" "logos-package-manager-module" ]; hasTests = false; };
  logos-storage-module           = { deps = [ "logos-cpp-sdk" "logos-liblogos" ]; hasTests = false; };
  logos-storage-ui               = { deps = [ "logos-cpp-sdk" "logos-liblogos" "logos-capability-module" "logos-storage-module" "logos-design-system" ]; hasTests = false; };
  logos-wallet-module            = { deps = [ "logos-cpp-sdk" "logos-liblogos" ]; hasTests = false; };
  logos-wallet-ui                = { deps = [ "logos-cpp-sdk" "logos-liblogos" "logos-capability-module" "logos-wallet-module" ]; hasTests = false; };
  logos-blockchain-module        = { deps = [ "logos-cpp-sdk" "logos-liblogos" "logos-module-viewer" ]; hasTests = false; };
  logos-blockchain-ui            = { deps = [ "logos-cpp-sdk" "logos-liblogos" "logos-capability-module" "logos-blockchain-module" "logos-design-system" ]; hasTests = false; };
  logos-execution-zone-wallet-ui = { deps = [ "logos-cpp-sdk" "logos-liblogos" "logos-capability-module" "nix-bundle-lgx" "logos-package-manager-module" "logos-execution-zone-module" "logos-design-system" ]; hasTests = false; };
  logos-execution-zone-module    = { deps = [ "logos-cpp-sdk" "logos-liblogos" "logos-module-viewer" ]; hasTests = false; };
  logos-libp2p-module            = { deps = [ "logos-module-builder" ]; hasTests = true; };
  logos-webview-app              = { deps = [ "logos-cpp-sdk" "logos-liblogos" ]; hasTests = false; };
  counter_qml                    = { deps = [ "logos-cpp-sdk" ]; hasTests = false; };
  counter                        = { deps = [ "logos-cpp-sdk" ]; hasTests = false; };
  logos-design-system            = { deps = [ "logos-cpp-sdk" ]; hasTests = false; };
  logos-js-sdk                   = { deps = [ "logos-cpp-sdk" "logos-liblogos" "logos-capability-module" ]; hasTests = false; };
  logos-nim-sdk                  = { deps = [ "logos-cpp-sdk" "logos-liblogos" ]; hasTests = false; };
  logos-rust-sdk                 = { deps = []; hasTests = false; };
  logos-test-modules             = { deps = [ "logos-liblogos" "logos-module-builder" ]; hasTests = true; };
  logos-modules                  = { deps = [ "logos-cpp-sdk" "logos-package" ]; hasTests = false; };
  logos-module-viewer            = { deps = [ "logos-cpp-sdk" "logos-liblogos" "logos-capability-module" "logos-package-manager-module" ]; hasTests = false; };
}
