{
  description = "Logos Workspace — unified multi-repo development environment";

  # ── Inputs ─────────────────────────────────────────────────────────────────
  #
  # The bulk of this block is auto-generated by `ws sync-graph` from each
  # repo's flake.lock.  Nix's flake parser requires `inputs` to be a literal
  # attrset (no `let`, `//`, `import`, or `builtins.mapAttrs` allowed), so
  # the per-repo follows can't be computed at evaluation time — they must
  # be written into this file directly.
  #
  # To regenerate after editing any repo's flake inputs:
  #
  #     ws sync-graph
  #
  # URL overrides (logos-blockchain org, tutorial sub-flakes) and manual
  # follows overrides live in `scripts/ws` near the top of `cmd_sync_graph`.

  inputs = {
    # ── Manual: shared Nix infrastructure ──────────────────────────────────
    #
    # logos-nix pins the workspace's nixpkgs (and therefore Qt).  Overriding
    # logos-nix here propagates to ALL downstream consumers via the auto-
    # generated follows below.
    logos-nix.url = "github:logos-co/logos-nix";
    nixpkgs.follows = "logos-nix/nixpkgs";
    # Pinned explicitly because logos-blockchain-module's upstream lock
    # currently references an invalid commit-ish via /0.2.1.
    logos-blockchain.url = "github:logos-blockchain/logos-blockchain/88941ff33f2e028591b9d0ed2549a328d54f0cfa";

    # BEGIN AUTO-INPUTS — generated by `ws sync-graph`, do not edit by hand
    logos-protocol = {
      url = "github:logos-co/logos-protocol/8bbc027c99505c3c2f043265f8c1ae8ff899bdff";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-qt-sdk = {
      url = "github:logos-co/logos-qt-sdk/03e489b16f9401526e52c0fdbc1e72cbf9fb1144";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-cpp-sdk = {
      url = "github:logos-co/logos-cpp-sdk/3f34c0b216c8fbdbf2093056b9f0fc53d89f05a1";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-view-module-runtime = {
      url = "github:logos-co/logos-view-module-runtime/42d9140811088f6ac0fcc3ccfc26d647afef1c35";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-module-client = {
      url = "github:logos-co/logos-module-client/351f282055659a9d8ccf0e6411c2683256906958";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.logos-qt-sdk.follows = "logos-qt-sdk";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-module = {
      url = "github:logos-co/logos-module/f71d16ddc5779b50b188b3a3928a37c9ce90b2a1";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package.follows = "logos-package";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-liblogos = {
      url = "github:logos-co/logos-liblogos/db45024f5c45ce5fc00ab76a6921985839ad7355";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-module.follows = "logos-module";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package-manager.follows = "logos-package-manager";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.logos-qt-sdk.follows = "logos-qt-sdk";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.process-stats.follows = "process-stats";
    };
    logos-logoscore-cli = {
      url = "github:logos-co/logos-logoscore-cli/6a0a2f4e96aa078a0a30080595075bcf46fb9a5d";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package-downloader-module.follows = "logos-package-downloader-module";
      inputs.logos-package-manager.follows = "logos-package-manager";
      inputs.logos-package-manager-module.follows = "logos-package-manager-module";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.nix-bundle-appimage.follows = "nix-bundle-appimage";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-capability-module = {
      url = "github:logos-co/logos-capability-module/1a1b8b5a1167931afbf41ebaafbe76034e6357a0";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-package = {
      url = "github:logos-co/logos-package/d759f34b095db14945ab0a38f6e1e924eafc3758";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-plugin-qt = {
      url = "github:logos-co/logos-plugin-qt/3a471be14af66d099827ee712ec8c40ead701340";
      inputs.logos-module.follows = "logos-module";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-module-builder = {
      url = "github:logos-co/logos-module-builder/4b7998272c5ec014bcac4bf1c7dbe7602c63a3c1";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-design-system.follows = "logos-design-system";
      inputs.logos-module.follows = "logos-module";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-plugin-core.follows = "logos-plugin-qt";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.logos-qt-sdk.follows = "logos-qt-sdk";
      inputs.logos-rust-sdk.follows = "logos-rust-sdk";
      inputs.logos-standalone-app.follows = "logos-standalone-app";
      inputs.logos-view-module-runtime.follows = "logos-view-module-runtime";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-bundle-dir = {
      url = "github:logos-co/nix-bundle-dir/ffc410b7f2bab32b1c2ceb347c56902e7321049c";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-bundle-lgx = {
      url = "github:logos-co/nix-bundle-lgx/d3445f62f9b0b1b3b8ca2193589c1051ff9e1a9e";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package.follows = "logos-package";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-bundle-appimage = {
      url = "github:logos-co/nix-bundle-appimage/04a3cf89f8ba3dc20f08a8e2b6c337a672bceda7";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-bundle-macos-app = {
      url = "github:logos-co/nix-bundle-macos-app/140f4ec32ebfb9790c1e5b1f6e46dff3d2b20cfd";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-standalone-app = {
      url = "github:logos-co/logos-standalone-app/9afc7310baa739397e1d80725dd6345c0b2176f8";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-design-system.follows = "logos-design-system";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.logos-view-module-runtime.follows = "logos-view-module-runtime";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-basecamp = {
      url = "github:logos-co/logos-basecamp/2c2022762b397e5c5657a480bab9981466211e35";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-design-system.follows = "logos-design-system";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-module.follows = "logos-module";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package.follows = "logos-package";
      inputs.logos-package-downloader-module.follows = "logos-package-downloader-module";
      inputs.logos-package-manager.follows = "logos-package-manager";
      inputs.logos-package-manager-module.follows = "logos-package-manager-module";
      inputs.logos-package-manager-ui.follows = "logos-package-manager-ui";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.logos-qt-sdk.follows = "logos-qt-sdk";
      inputs.logos-view-module-runtime.follows = "logos-view-module-runtime";
      inputs.nix-bundle-appimage.follows = "nix-bundle-appimage";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nix-bundle-macos-app.follows = "nix-bundle-macos-app";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-accounts-module = {
      url = "github:logos-co/logos-accounts-module/4fd4cb0be3d281b4a9b3303f892b2b265edb2a62";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-accounts-ui = {
      url = "github:logos-co/logos-accounts-ui/324b2c6e0aa76ecbed3a2d2922fd16093539eb25";
      inputs.accounts_module.follows = "logos-accounts-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-chat-module = {
      url = "github:logos-co/logos-chat-module/7c446e03bd71ccf2fbd3b472493e275b1c4edc5d";
      inputs.logos-delivery-module.follows = "logos-delivery-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-chat-ui = {
      url = "github:logos-co/logos-chat-ui/78af24d6e8659bbe0f357809e8c2cabd4088d93b";
      inputs.chat_module.follows = "logos-chat-module";
      inputs.logos-delivery-module.follows = "logos-delivery-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-package-manager = {
      url = "github:logos-co/logos-package-manager/d3af2972f51d9c542537d80d60ad8d20282ddcd1";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package.follows = "logos-package";
      inputs.nix-bundle-appimage.follows = "nix-bundle-appimage";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-package-downloader = {
      url = "github:logos-co/logos-package-downloader/9fc7d17650e30a1e2315d98283bc46fb3a3ee8b9";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package.follows = "logos-package";
      inputs.nix-bundle-appimage.follows = "nix-bundle-appimage";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-package-manager-module = {
      url = "github:logos-co/logos-package-manager-module/2c68b5a55f8c1fbb2fcd3fbac702632f1cedbe4c";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logos-package-manager.follows = "logos-package-manager";
    };
    logos-package-downloader-module = {
      url = "github:logos-co/logos-package-downloader-module/a49fe22495238b3856e6e46ea630b1b94452856f";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logos-package-downloader.follows = "logos-package-downloader";
    };
    logos-package-manager-ui = {
      url = "github:logos-co/logos-package-manager-ui/bb18c253411664623667cead69b079c65ebb22f1";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logos-package.follows = "logos-package";
      inputs.package_downloader.follows = "logos-package-downloader-module";
      inputs.package_manager.follows = "logos-package-manager-module";
    };
    logos-storage-module = {
      url = "github:logos-co/logos-storage-module/2658e89fb8079a2888225f930ae77faedb0bf26d";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-storage-ui = {
      url = "github:logos-co/logos-storage-ui/0a5485e6a8768e2ace77ef8711fb07c9020d72df";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
      inputs.storage_module.follows = "logos-storage-module";
    };
    logos-wallet-module = {
      url = "github:logos-co/logos-wallet-module/f6f9c160410db824531f42dd8b27ccecd39ca589";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-wallet-ui = {
      url = "github:logos-co/logos-wallet-ui/26f8f5bebd511e91e29019e1e7c892bd5753439d";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
      inputs.wallet_module.follows = "logos-wallet-module";
    };
    logos-delivery-module = {
      url = "github:logos-co/logos-delivery-module/5a2d584aadaade540440122e680e642f77d4f69b";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
    };
    logos-delivery-demo = {
      url = "github:logos-co/logos-delivery-demo/4e1d04091014c6f8b0c7c643bb446104bf3e0563";
      inputs.delivery_module.follows = "logos-delivery-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-blockchain-module = {
      url = "github:logos-blockchain/logos-blockchain-module/e3add5beea00295f464b35a9008ccfb9d7f1ff08";
      inputs.logos-blockchain.follows = "logos-blockchain";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-blockchain-ui = {
      url = "github:logos-blockchain/logos-blockchain-ui/f9841e88391354aa17e78acfa1ac726c7b4c67a7";
      inputs.blockchain_module.follows = "logos-blockchain-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
      inputs.process-stats.follows = "process-stats";
    };
    logos-execution-zone-wallet-ui = {
      url = "github:logos-blockchain/logos-execution-zone-wallet-ui/13b5d8e7af8f9eb38758a2d49b25a90dfe40cc76";
      inputs.lez_core.follows = "logos-execution-zone-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
    };
    logos-execution-zone-module = {
      url = "github:logos-blockchain/logos-execution-zone-module/825d2a41262b9882aa0f9ca837cb03635f7980c2";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
    };
    logos-libp2p-module = {
      url = "github:logos-co/logos-libp2p-module/7d78bb772b8c728ca3ea881158057f6faf9eda24";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logoscore-cli.follows = "logos-logoscore-cli";
      inputs.package-manager.follows = "logos-package-manager";
      inputs.libp2p.url = "github:vacp2p/nim-libp2p/7c73484cc0c57a5f649dd3d277cef1c7c4de28f0";
    };
    logos-webview-app = {
      url = "github:logos-co/logos-webview-app/b5d1bb40da6ba550076069a10cf9beaac45aa515";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
    };
    counter_qml.url = "github:logos-co/counter_qml/8029a894f4221f9284efabbedcee7d9d18929777";
    counter = {
      url = "github:logos-co/counter/8cd0db213d4c42206e03004bcce3306466a3692a";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-design-system = {
      url = "github:logos-co/logos-design-system/88330d04968954be956311b0be429048a41da2ea";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nix-bundle-appimage.follows = "nix-bundle-appimage";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nix-bundle-macos-app.follows = "nix-bundle-macos-app";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-js-sdk = {
      url = "github:logos-co/logos-js-sdk/22ee15fd35c4bc880537ce4842079bf3460703d5";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-nim-sdk = {
      url = "github:logos-co/logos-nim-sdk/df1f21906e661d96f5e4bda172cb9a619292b603";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-rust-sdk.url = "github:logos-co/logos-rust-sdk/95f3cb168d59ad3144ac15f65a7bacff66ce3335";
    logos-logoscore-py = {
      url = "github:logos-co/logos-logoscore-py/75f2aca0188f390a1cf3ec930d8466ed2ed7775c";
      inputs.logos-logoscore-cli.follows = "logos-logoscore-cli";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-test-modules.follows = "logos-test-modules";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-test-modules = {
      url = "github:logos-co/logos-test-modules/23870fcb085c93c7b8e6ea71d37d2fe1aa03e200";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-logoscore-cli.follows = "logos-logoscore-cli";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    process-stats = {
      url = "github:logos-co/process-stats/6e0aade77db1b03cc08559c5700c687fa6f00269";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-module-viewer = {
      url = "github:logos-co/logos-module-viewer/f8914691f3ac8be78b894d01b5d5ec6ce25d44f3";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-package-manager.follows = "logos-package-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-evm-net-proxy.url = "github:logos-co/logos-evm-net-proxy/e2d0c01bf066d2a8cd085d6bdc04ab1263e00c42";
    logos-evm-keystore-module = {
      url = "github:logos-co/logos-evm-keystore-module/2318c679e2b7176967bd45052f3d64b2a8b06931";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-evm-eth-rpc-module = {
      url = "github:logos-co/logos-evm-eth-rpc-module/49158948e873326a176dc136f2889daab8053d43";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-evm-token-list-module = {
      url = "github:logos-co/logos-evm-token-list-module/213e62853fe817bad02db8588b8be6ecd1e72211";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-evm-uniswap-module = {
      url = "github:logos-co/logos-evm-uniswap-module/35f286b98cd08f1a9aff7eda8b55eb208a0841be";
      inputs.eth_rpc_module.follows = "logos-evm-eth-rpc-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-evm-railgun-module = {
      url = "github:logos-co/logos-evm-railgun-module/bb82759805ee888fc3e2fb689693cbb4897b81fd";
      inputs.eth_rpc_module.follows = "logos-evm-eth-rpc-module";
      inputs.keystore_module.follows = "logos-evm-keystore-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-evm-wallet-backend-module = {
      url = "github:logos-co/logos-evm-wallet-backend-module/25cadae21d7d45f773d88a14baec3a0c824d80f3";
      inputs.eth_rpc_module.follows = "logos-evm-eth-rpc-module";
      inputs.keystore_module.follows = "logos-evm-keystore-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.token_list_module.follows = "logos-evm-token-list-module";
      inputs.uniswap_module.follows = "logos-evm-uniswap-module";
    };
    logos-evm-wallet-ui = {
      url = "github:logos-co/logos-evm-wallet-ui/2007226b8920038b100deef5de176979d8df8f29";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.wallet_backend_module.follows = "logos-evm-wallet-backend-module";
    };
    # END AUTO-INPUTS
  };

  outputs = { self, nixpkgs, ... }@inputs:
    let
      systems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      forAllSystems = fn: nixpkgs.lib.genAttrs systems fn;

      depGraph = import ./nix/dep-graph.nix;

      # Every logos flake input we iterate over for packages/apps/checks.
      # Excludes `logos-nix` (it's a nixpkgs pin, not a buildable repo).
      repoInputNames = builtins.attrNames
        (builtins.removeAttrs depGraph [ "logos-nix" ]);

      # Mapping from flake input name → submodule directory name under repos/.
      # Only entries where the names differ need to be listed.
      inputToDirOverrides = {
        "logos-calc-module" = "logos-tutorial/logos-calc-module";
        "logos-calc-ui"     = "logos-tutorial/logos-calc-ui";
        "logos-calc-ui-cpp" = "logos-tutorial/logos-calc-ui-cpp";
      };

      inputToDir = name: inputToDirOverrides.${name} or name;

    in {

      # ── Packages ──────────────────────────────────────────────────────────
      # nix build .#logos-cpp-sdk          → default package
      # nix build .#logos-basecamp          → default package
      # nix build .#logos-basecamp--portable → non-default output
      # nix build .#logos-liblogos--portable
      # nix bundle --bundler .#nix-bundle-lgx .#logos-chat-module--lib
      # All repo package outputs are exposed: default as the repo name,
      # non-default as <repo>--<output>.
      packages = forAllSystems (system:
        let
          # Collect all package outputs from all repos.
          # Each repo's packages are forwarded lazily — the value is not
          # evaluated until someone actually builds it, so broken store
          # paths or missing files won't cause errors at evaluation time.
          allPkgs = builtins.foldl' (acc: name:
            let
              repoPkgs = (inputs.${name}.packages.${system} or {});
              outNames = builtins.attrNames repoPkgs;
            in
            acc // builtins.listToAttrs (map (outName:
              let
                attrName = if outName == "default" then name else "${name}--${outName}";
              in
              { name = attrName; value = repoPkgs.${outName}; }
            ) outNames)
          ) {} repoInputNames;
        in allPkgs
      );

      # ── Apps ──────────────────────────────────────────────────────────────
      # nix run .#logos-standalone-app -- --plugin ./result/lib/
      # Forwards apps outputs from all repos. Default app exposed as repo name,
      # non-default as <repo>--<output>.
      apps = forAllSystems (system:
        builtins.foldl' (acc: name:
          let
            repoApps = (inputs.${name}.apps.${system} or {});
            outNames = builtins.attrNames repoApps;
          in
          acc // builtins.listToAttrs (map (outName:
            let
              attrName = if outName == "default" then name else "${name}--${outName}";
            in
            { name = attrName; value = repoApps.${outName}; }
          ) outNames)
        ) {} repoInputNames
      );

      # ── Dev Shells ────────────────────────────────────────────────────────
      # nix develop          → workspace shell (ws CLI + common tools)
      # nix develop .#logos-cpp-sdk → that repo's own devShell
      # nix develop          → workspace shell with ws CLI + common tools
      # For sub-repo devShells use: nix develop path:./repos/<repo-name>
      #   or: ws develop <repo-name>
      devShells = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; };
          # Always delegates to the live scripts/ws in the workspace,
          # without needing to rebuild the devshell. Falls back to the
          # flake directory if LOGOS_WORKSPACE_ROOT is not set.
          wsScript = pkgs.writeShellScriptBin "ws" ''
            exec "''${LOGOS_WORKSPACE_ROOT:-${builtins.toString ./.}}/scripts/ws" "$@"
          '';
        in {
          default = import ./nix/devshell.nix { inherit pkgs wsScript; };
        }
      );

      # ── Checks ────────────────────────────────────────────────────────────
      # nix flake check        → run ALL repo checks
      # nix build .#checks.x86_64-linux.logos-cpp-sdk--test
      checks = forAllSystems (system:
        builtins.foldl' (acc: name:
          let
            result = builtins.tryEval (inputs.${name}.checks.${system} or {});
            repoChecks = if result.success then result.value else {};
            prefixed = nixpkgs.lib.mapAttrs'
              (cname: drv: { name = "${name}--${cname}"; value = drv; })
              repoChecks;
          in
          acc // prefixed
        ) {} repoInputNames
      );

      # ── Bundlers ──────────────────────────────────────────────────────────
      # Forwards nix-bundle-lgx bundlers so scripts can use "$WORKSPACE_ROOT"
      # as the --bundler reference.
      bundlers = forAllSystems (system:
        inputs.nix-bundle-lgx.bundlers.${system}
      );

      # ── Lib (for programmatic use) ────────────────────────────────────────
      lib = {
        inherit repoInputNames inputToDir;
        # Dependency graph: input name → { deps, follows, hasTests }
        depGraph = depGraph;
      };
    };
}
