{
  description = "Logos Workspace — unified multi-repo development environment";

  # ── Inputs ─────────────────────────────────────────────────────────────────
  #
  # The bulk of this block is auto-generated by `ws sync-graph` from each
  # repo's flake.lock.  Nix's flake parser requires `inputs` to be a literal
  # attrset (no `let`, `//`, `import`, or `builtins.mapAttrs` allowed), so
  # the per-repo follows can't be computed at evaluation time — they must
  # be written into this file directly.
  #
  # To regenerate after editing any repo's flake inputs:
  #
  #     ws sync-graph
  #
  # URL overrides (logos-blockchain org, tutorial sub-flakes) and manual
  # follows overrides live in `scripts/ws` near the top of `cmd_sync_graph`.

  inputs = {
    # ── Manual: shared Nix infrastructure ──────────────────────────────────
    #
    # logos-nix pins the workspace's nixpkgs (and therefore Qt).  Overriding
    # logos-nix here propagates to ALL downstream consumers via the auto-
    # generated follows below.
    logos-nix.url = "github:logos-co/logos-nix/6e0f4a7120fced10829b0b3a698ff619a11d4605";
    nixpkgs.follows = "logos-nix/nixpkgs";
    # Pinned explicitly because logos-blockchain-module's upstream lock
    # currently references an invalid commit-ish via /0.2.1.
    logos-blockchain.url = "github:logos-blockchain/logos-blockchain/88941ff33f2e028591b9d0ed2549a328d54f0cfa";

    # logos-lidl is the LIDL frontend (lexer/parser/AST/serializer/validator)
    # that EVERY code generator links — cpp-sdk's, qt-sdk's, plugin-qt's and
    # rust-sdk's.  It is declared MANUALLY, here, and not in the auto-block
    # below, for two reasons:
    #
    #   1. logos-lidl is not registered in `scripts/ws`'s REPOS table, so
    #      `ws sync-graph` never emitted it as a workspace input.  With no
    #      root to follow, each consumer resolved logos-lidl from its OWN
    #      lock and the closure carried THREE revisions at once (8c95d4f0,
    #      35f33d87, ffeebf2e).  A hand-added entry in the auto-block gets
    #      wiped by the next sync-graph; an entry here survives.
    #   2. sync-graph pins auto-block URLs to the submodule's checked-out
    #      HEAD, which would silently re-pin this the moment anyone runs it
    #      with a different commit checked out.  This pin is curated.
    #
    # The rev is a DESCENDANT of all three revisions that were previously in
    # the closure — the history is strictly linear, so unifying here loses
    # nothing:
    #
    #   8c95d4f0  descriptions + AST<->JSON + C ABI
    #     -> 35f33d87  two-state optionality (adds the fieldIsOptional() /
    #                  optionalValueType() accessors that cpp-sdk's
    #                  lidl_compat.h and qt-sdk's generator `using`-import;
    #                  unifying DOWN to 8c95d4f0 would not COMPILE)
    #       -> ffeebf2e  x86_64-windows cross target (flake-only)
    #         -> 39015299  logos_lidl_c_shared, the SHARED liblogos_lidl_c
    #                      that logos-js-sdk's koffi codegen dlopen()s
    #                      (CMakeLists-only, purely additive)
    #
    # 39015299 is on feat/sdk-codegen-phase-a rather than master: master
    # (ffeebf2e) does not carry the shared library yet.  Re-point at master
    # once that branch merges.
    logos-lidl = {
      url = "github:logos-co/logos-lidl/39015299b913ac6c81a9808268141b3bdc046b4e";
      inputs.logos-nix.follows = "logos-nix";
    };

    # BEGIN AUTO-INPUTS — generated by `ws sync-graph`, do not edit by hand
    logos-protocol = {
      url = "github:logos-co/logos-protocol/c8bab12834dbf92155b483546875e6078d17c74e";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-qt-sdk = {
      url = "github:logos-co/logos-qt-sdk/8a06b870e59afca3392de2bddf8eec5fe3b85225";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-lidl.follows = "logos-lidl";
      inputs.logos-nix.follows = "logos-nix";
      # Load-bearing, not tidiness. logos-qt-sdk no longer compiles the Qt host
      # runtime — it re-exports logos-plugin-qt's logos-qt-host. Without this
      # follows the SDK resolves plugin-qt from its OWN lock while everything
      # else here resolves the workspace's, and the closure ends up with two
      # logos-qt-host prefixes: two LogosAPIs, two TokenManager singletons.
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-cpp-sdk = {
      url = "github:logos-co/logos-cpp-sdk/a04b27888e1d126578f639ed46dae0c777990a10";
      inputs.logos-lidl.follows = "logos-lidl";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-view-module-runtime = {
      url = "github:logos-co/logos-view-module-runtime/5510acd9eb7fcd49e420c9e530679edfa8f315ab";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-module-client = {
      url = "github:logos-co/logos-module-client/e0e58286ce2de85b9bf7b86c5472ccce68225dea";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-module = {
      url = "github:logos-co/logos-module/2ec64c4a65f8966b5137cdba3a19a6498ce17b6d";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-module-loader-qt = {
      url = "github:logos-co/logos-module-loader-qt/06134bfcb726a53b889ffa56e43b08e94938b6cf";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-module.follows = "logos-module";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.logos-qt-sdk.follows = "logos-qt-sdk";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-liblogos = {
      url = "github:logos-co/logos-liblogos/f2a15ef3022d8fb71dac3d612c8edec839fc51e7";
      inputs.default-module-loader.follows = "logos-module-loader-qt";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-module.follows = "logos-module";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package-manager.follows = "logos-package-manager";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.logos-qt-sdk.follows = "logos-qt-sdk";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.process-stats.follows = "process-stats";
    };
    logos-logoscore-cli = {
      url = "github:logos-co/logos-logoscore-cli/e081c19a7700a4316b8cccfca29384b957f18fd7";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.logos-test-modules.follows = "logos-test-modules";
      inputs.nix-bundle-appimage.follows = "nix-bundle-appimage";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-capability-module = {
      url = "github:logos-co/logos-capability-module/07dba1fb32ec889e28848c7730f0d5b3912a5b5b";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-package = {
      url = "github:logos-co/logos-package/8d4236f9453bce8b44dfd2f85a5006af993b7ed2";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    # cc24fa1c is the tip of feat/b4-qt-host-windows-target — the SUPERSET of
    # the two branches carrying the qt-host split.  The sibling
    # feat/b4-qt-host-windows-target-8ccb1fc (989f6ae) is a reduced
    # re-baselining that omits the LogosModule.cmake/view-template unification;
    # every consumer here (liblogos, qt-sdk, standalone-app, logoscore-cli,
    # module-builder, test-modules, view-module-runtime, basecamp) pins
    # cc24fa1c, so taking 989f6ae would put a SECOND logos-qt-host in the
    # closure: two LogosAPIs, two TokenManager singletons.  repos/logos-plugin-qt
    # is checked out on this same rev so `ws sync-graph` cannot walk it back.
    logos-plugin-qt = {
      url = "github:logos-co/logos-plugin-qt/cc24fa1c0c43b2d96c1dc165ee545a0321318b59";
      inputs.logos-lidl.follows = "logos-lidl";
      inputs.logos-module.follows = "logos-module";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-module-builder = {
      url = "github:logos-co/logos-module-builder/c60d4a9cf32cb5281909e53159c9c4cfeb993847";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-design-system.follows = "logos-design-system";
      inputs.logos-module.follows = "logos-module";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-plugin-core.follows = "logos-plugin-qt";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.logos-qt-sdk.follows = "logos-qt-sdk";
      inputs.logos-rust-sdk.follows = "logos-rust-sdk";
      inputs.logos-standalone-app.follows = "logos-standalone-app";
      inputs.logos-view-module-runtime.follows = "logos-view-module-runtime";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-bundle-dir = {
      url = "github:logos-co/nix-bundle-dir/4f72d7a64dd83979d771c17161f23ebc9dbedb40";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-bundle-lgx = {
      url = "github:logos-co/nix-bundle-lgx/b49074a8e1157832002b11d3d254c1aaa4b96680";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package.follows = "logos-package";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-bundle-appimage = {
      url = "github:logos-co/nix-bundle-appimage/8fcc56b5afcc313ca917cf3487be082ae2f0184c";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-bundle-macos-app = {
      url = "github:logos-co/nix-bundle-macos-app/d6b0cc518e599ab7a52258bf3e1f8123c8a01d31";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-standalone-app = {
      url = "github:logos-co/logos-standalone-app/39f4f2b507846bf6383f60a4c61d8a9445009227";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-design-system.follows = "logos-design-system";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.logos-view-module-runtime.follows = "logos-view-module-runtime";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-basecamp = {
      url = "github:logos-co/logos-basecamp/8bfc36915efff975812e5158c819671cfbf08e0d";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-design-system.follows = "logos-design-system";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-module.follows = "logos-module";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package.follows = "logos-package";
      inputs.logos-package-downloader-module.follows = "logos-package-downloader-module";
      inputs.logos-package-manager.follows = "logos-package-manager";
      inputs.logos-package-manager-module.follows = "logos-package-manager-module";
      inputs.logos-package-manager-ui.follows = "logos-package-manager-ui";
      inputs.logos-protocol.follows = "logos-protocol";
      inputs.logos-view-module-runtime.follows = "logos-view-module-runtime";
      inputs.nix-bundle-appimage.follows = "nix-bundle-appimage";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nix-bundle-macos-app.follows = "nix-bundle-macos-app";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-accounts-module = {
      url = "github:logos-co/logos-accounts-module/4fd4cb0be3d281b4a9b3303f892b2b265edb2a62";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-accounts-ui = {
      url = "github:logos-co/logos-accounts-ui/324b2c6e0aa76ecbed3a2d2922fd16093539eb25";
      inputs.accounts_module.follows = "logos-accounts-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-chat-module = {
      url = "github:logos-co/logos-chat-module/33c624d0e6ea8444486d6bfe68aa07450315bdb6";
      inputs.logos-delivery-module.follows = "logos-delivery-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-chat-ui = {
      url = "github:logos-co/logos-chat-ui/8d6a9feaa6eef3e9714d3aed3867d20337972542";
      inputs.chat_module.follows = "logos-chat-module";
      inputs.logos-delivery-module.follows = "logos-delivery-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-package-manager = {
      url = "github:logos-co/logos-package-manager/202af6fa0f0f4493bc59c8a609dff9326f78a18d";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package.follows = "logos-package";
      inputs.nix-bundle-appimage.follows = "nix-bundle-appimage";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-package-downloader = {
      url = "github:logos-co/logos-package-downloader/6fcf682539c501e927d72393872a4f36d6b1d2a9";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package.follows = "logos-package";
      inputs.nix-bundle-appimage.follows = "nix-bundle-appimage";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-package-manager-module = {
      url = "github:logos-co/logos-package-manager-module/cad6bab044d09eb54fe9a8efb20ed94694eb44ff";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logos-package-manager.follows = "logos-package-manager";
    };
    logos-package-downloader-module = {
      url = "github:logos-co/logos-package-downloader-module/2298842e8d5e8118d2268952fb08017152b8d433";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logos-package-downloader.follows = "logos-package-downloader";
    };
    logos-package-manager-ui = {
      url = "github:logos-co/logos-package-manager-ui/c932e1c4bfb5e5e2e04abfb7e561ed19ba18ffca";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logos-package.follows = "logos-package";
      inputs.package_downloader.follows = "logos-package-downloader-module";
      inputs.package_manager.follows = "logos-package-manager-module";
    };
    logos-storage-module = {
      url = "github:logos-co/logos-storage-module/8feb7cc0f7806bc2b25faa884e1bb9076b993969";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-storage-ui = {
      url = "github:logos-co/logos-storage-ui/823be657d236afe824b9804d6aee69c14b1d4507";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
      inputs.storage_module.follows = "logos-storage-module";
    };
    logos-wallet-module = {
      url = "github:logos-co/logos-wallet-module/f6f9c160410db824531f42dd8b27ccecd39ca589";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-wallet-ui = {
      url = "github:logos-co/logos-wallet-ui/26f8f5bebd511e91e29019e1e7c892bd5753439d";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
      inputs.wallet_module.follows = "logos-wallet-module";
    };
    logos-delivery-module = {
      url = "github:logos-co/logos-delivery-module/3f8a0ed99afae349fec8013442638e7569ac2cf3";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
    };
    logos-delivery-demo = {
      url = "github:logos-co/logos-delivery-demo/b5fec54843a20290fdc847762bdbc7f2d7217da1";
      inputs.delivery_module.follows = "logos-delivery-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-blockchain-module = {
      url = "github:logos-blockchain/logos-blockchain-module/581323e9e587a3b8057f8f63a9ade1ff1892111a";
      inputs.logos-blockchain.follows = "logos-blockchain";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-blockchain-ui = {
      url = "github:logos-blockchain/logos-blockchain-ui/600d98bbbd01ac874eed48b4cacf4cd0609bfb2b";
      inputs.blockchain_module.follows = "logos-blockchain-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
    };
    logos-execution-zone-wallet-ui = {
      url = "github:logos-blockchain/logos-execution-zone-wallet-ui/da1b021db5315eccd1e39835268bbc08633adc12";
      inputs.lez_core.follows = "logos-execution-zone-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
    };
    logos-execution-zone-module = {
      url = "github:logos-blockchain/logos-execution-zone-module/033f807a3b1690fb2f8e661cb8067646b8a98242";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
    };
    logos-libp2p-module = {
      url = "github:logos-co/logos-libp2p-module/7b4b776b26d96e2a0c794827c77bb6eb89da5100";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logoscore-cli.follows = "logos-logoscore-cli";
      inputs.package-manager.follows = "logos-package-manager";
      inputs.libp2p.url = "github:vacp2p/nim-libp2p/7c73484cc0c57a5f649dd3d277cef1c7c4de28f0";
    };
    logos-webview-app = {
      url = "github:logos-co/logos-webview-app/b5d1bb40da6ba550076069a10cf9beaac45aa515";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
    };
    counter_qml.url = "github:logos-co/counter_qml/8029a894f4221f9284efabbedcee7d9d18929777";
    counter = {
      url = "github:logos-co/counter/47edd6bad49e4129d6c7c169246de7ba5c67d8a9";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-design-system = {
      url = "github:logos-co/logos-design-system/fd4978713921e087c40f4a6a52a3e5f60f6104bd";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nix-bundle-appimage.follows = "nix-bundle-appimage";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nix-bundle-macos-app.follows = "nix-bundle-macos-app";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-js-sdk = {
      url = "github:logos-co/logos-js-sdk/1847487178a90cdd316d00fb3faaf91b0c123d05";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-nim-sdk = {
      url = "github:logos-co/logos-nim-sdk/1f6a167e44f762eec98e403b261cfc0b6eb263e3";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-rust-sdk.url = "github:logos-co/logos-rust-sdk/be0dedad0fbef00c497e2e5e83ef03a000abcee6";
    # logos-rust-sdk was the last consumer still resolving logos-lidl from its
    # own lock (8c95d4f0) — the sole root-level repo that this unification
    # moves ACROSS the two-state-optionality commit.  Safe: lidl-gen reads the
    # JSON wire form through serde with no deny_unknown_fields, and that
    # commit only ADDS keys (isOptional/valueType/returnIsOptional), leaving
    # every pre-existing key and the C ABI byte-identical.
    logos-rust-sdk.inputs.logos-lidl.follows = "logos-lidl";
    logos-logoscore-py = {
      url = "github:logos-co/logos-logoscore-py/6e081b2d2fd87a909b958aa8a97be445229acf75";
      inputs.logos-logoscore-cli.follows = "logos-logoscore-cli";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-test-modules.follows = "logos-test-modules";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-test-modules = {
      url = "github:logos-co/logos-test-modules/a639b93475bf135d283288c31b8499b7f4d09f92";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-logoscore-cli.follows = "logos-logoscore-cli";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    process-stats = {
      url = "github:logos-co/process-stats/33ace1270f90c89b3565e803139c0970fcd1ce8f";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-module-viewer = {
      url = "github:logos-co/logos-module-viewer/b6489c1aab8c1590fa127dbaedb39708f3614fbc";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-package-manager.follows = "logos-package-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-evm-net-proxy.url = "github:logos-co/logos-evm-net-proxy/564a730551b677ff8292144c3773a46d99a18b91";
    logos-evm-keystore-module = {
      url = "github:logos-co/logos-evm-keystore-module/1ac386973acf568b48bb52f7e17baf302fa55670";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-evm-eth-rpc-module = {
      url = "github:logos-co/logos-evm-eth-rpc-module/8a825cdbf0b78de4af30b6250e91b08d2e1ba1d7";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-evm-token-list-module = {
      url = "github:logos-co/logos-evm-token-list-module/25d5d6b2a96987bb2a757a0348c150baeb675e3b";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-evm-uniswap-module = {
      url = "github:logos-co/logos-evm-uniswap-module/df069a7eab47d705eb3b519092a5e41e85ddd7f1";
      inputs.eth_rpc_module.follows = "logos-evm-eth-rpc-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-evm-railgun-module = {
      url = "github:logos-co/logos-evm-railgun-module/b6d066932c62791c8be5b9a7344318d8df9a6156";
      inputs.eth_rpc_module.follows = "logos-evm-eth-rpc-module";
      inputs.keystore_module.follows = "logos-evm-keystore-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-evm-wallet-backend-module = {
      url = "github:logos-co/logos-evm-wallet-backend-module/584dbfe3195ec6dfe4c0d8b91fabb02ac2d963f4";
      inputs.eth_rpc_module.follows = "logos-evm-eth-rpc-module";
      inputs.keystore_module.follows = "logos-evm-keystore-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.railgun_module.follows = "logos-evm-railgun-module";
      inputs.token_list_module.follows = "logos-evm-token-list-module";
      inputs.uniswap_module.follows = "logos-evm-uniswap-module";
    };
    logos-evm-wallet-ui = {
      url = "github:logos-co/logos-evm-wallet-ui/68f7c4fe6005990dea38de67d6853d12d9045872";
      inputs.eth_rpc_module.follows = "logos-evm-eth-rpc-module";
      inputs.keystore_module.follows = "logos-evm-keystore-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.railgun_module.follows = "logos-evm-railgun-module";
      inputs.token_list_module.follows = "logos-evm-token-list-module";
      inputs.uniswap_module.follows = "logos-evm-uniswap-module";
      inputs.wallet_backend_module.follows = "logos-evm-wallet-backend-module";
    };
    # END AUTO-INPUTS
  };

  outputs = { self, nixpkgs, ... }@inputs:
    let
      systems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      forAllSystems = fn: nixpkgs.lib.genAttrs systems fn;

      depGraph = import ./nix/dep-graph.nix;

      # Every logos flake input we iterate over for packages/apps/checks.
      # Excludes `logos-nix` (it's a nixpkgs pin, not a buildable repo).
      repoInputNames = builtins.attrNames
        (builtins.removeAttrs depGraph [ "logos-nix" ]);

      # Mapping from flake input name → submodule directory name under repos/.
      # Only entries where the names differ need to be listed.
      inputToDirOverrides = {
        "logos-calc-module" = "logos-tutorial/logos-calc-module";
        "logos-calc-ui"     = "logos-tutorial/logos-calc-ui";
        "logos-calc-ui-cpp" = "logos-tutorial/logos-calc-ui-cpp";
      };

      inputToDir = name: inputToDirOverrides.${name} or name;

    in {

      # ── Packages ──────────────────────────────────────────────────────────
      # nix build .#logos-cpp-sdk          → default package
      # nix build .#logos-basecamp          → default package
      # nix build .#logos-basecamp--portable → non-default output
      # nix build .#logos-liblogos--portable
      # nix bundle --bundler .#nix-bundle-lgx .#logos-chat-module--lib
      # All repo package outputs are exposed: default as the repo name,
      # non-default as <repo>--<output>.
      packages = forAllSystems (system:
        let
          # Collect all package outputs from all repos.
          # Each repo's packages are forwarded lazily — the value is not
          # evaluated until someone actually builds it, so broken store
          # paths or missing files won't cause errors at evaluation time.
          allPkgs = builtins.foldl' (acc: name:
            let
              repoPkgs = (inputs.${name}.packages.${system} or {});
              outNames = builtins.attrNames repoPkgs;
            in
            acc // builtins.listToAttrs (map (outName:
              let
                attrName = if outName == "default" then name else "${name}--${outName}";
              in
              { name = attrName; value = repoPkgs.${outName}; }
            ) outNames)
          ) {} repoInputNames;
        in allPkgs
      );

      # ── Apps ──────────────────────────────────────────────────────────────
      # nix run .#logos-standalone-app -- --plugin ./result/lib/
      # Forwards apps outputs from all repos. Default app exposed as repo name,
      # non-default as <repo>--<output>.
      apps = forAllSystems (system:
        builtins.foldl' (acc: name:
          let
            repoApps = (inputs.${name}.apps.${system} or {});
            outNames = builtins.attrNames repoApps;
          in
          acc // builtins.listToAttrs (map (outName:
            let
              attrName = if outName == "default" then name else "${name}--${outName}";
            in
            { name = attrName; value = repoApps.${outName}; }
          ) outNames)
        ) {} repoInputNames
      );

      # ── Dev Shells ────────────────────────────────────────────────────────
      # nix develop          → workspace shell (ws CLI + common tools)
      # nix develop .#logos-cpp-sdk → that repo's own devShell
      # nix develop          → workspace shell with ws CLI + common tools
      # For sub-repo devShells use: nix develop path:./repos/<repo-name>
      #   or: ws develop <repo-name>
      devShells = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; };
          # Always delegates to the live scripts/ws in the workspace,
          # without needing to rebuild the devshell. Falls back to the
          # flake directory if LOGOS_WORKSPACE_ROOT is not set.
          wsScript = pkgs.writeShellScriptBin "ws" ''
            exec "''${LOGOS_WORKSPACE_ROOT:-${builtins.toString ./.}}/scripts/ws" "$@"
          '';
        in {
          default = import ./nix/devshell.nix { inherit pkgs wsScript; };
        }
      );

      # ── Checks ────────────────────────────────────────────────────────────
      # nix flake check        → run ALL repo checks
      # nix build .#checks.x86_64-linux.logos-cpp-sdk--test
      checks = forAllSystems (system:
        builtins.foldl' (acc: name:
          let
            result = builtins.tryEval (inputs.${name}.checks.${system} or {});
            repoChecks = if result.success then result.value else {};
            prefixed = nixpkgs.lib.mapAttrs'
              (cname: drv: { name = "${name}--${cname}"; value = drv; })
              repoChecks;
          in
          acc // prefixed
        ) {} repoInputNames
      );

      # ── Bundlers ──────────────────────────────────────────────────────────
      # Forwards nix-bundle-lgx bundlers so scripts can use "$WORKSPACE_ROOT"
      # as the --bundler reference.
      bundlers = forAllSystems (system:
        inputs.nix-bundle-lgx.bundlers.${system}
      );

      # ── Lib (for programmatic use) ────────────────────────────────────────
      lib = {
        inherit repoInputNames inputToDir;
        # Dependency graph: input name → { deps, follows, hasTests }
        depGraph = depGraph;
      };
    };
}
