{
  description = "Logos Workspace — unified multi-repo development environment";

  # ── Inputs ─────────────────────────────────────────────────────────────────
  #
  # The bulk of this block is auto-generated by `ws sync-graph` from each
  # repo's flake.lock.  Nix's flake parser requires `inputs` to be a literal
  # attrset (no `let`, `//`, `import`, or `builtins.mapAttrs` allowed), so
  # the per-repo follows can't be computed at evaluation time — they must
  # be written into this file directly.
  #
  # To regenerate after editing any repo's flake inputs:
  #
  #     ws sync-graph
  #
  # URL overrides (logos-blockchain org, tutorial sub-flakes) and manual
  # follows overrides live in `scripts/ws` near the top of `cmd_sync_graph`.

  inputs = {
    # ── Manual: shared Nix infrastructure ──────────────────────────────────
    #
    # logos-nix pins the workspace's nixpkgs (and therefore Qt).  Overriding
    # logos-nix here propagates to ALL downstream consumers via the auto-
    # generated follows below.
    logos-nix.url = "github:logos-co/logos-nix";
    nixpkgs.follows = "logos-nix/nixpkgs";
    # Pinned explicitly because logos-blockchain-module's upstream lock
    # currently references an invalid commit-ish via /0.2.1.
    logos-blockchain.url = "github:logos-blockchain/logos-blockchain/88941ff33f2e028591b9d0ed2549a328d54f0cfa";

    # BEGIN AUTO-INPUTS — generated by `ws sync-graph`, do not edit by hand
    logos-cpp-sdk = {
      url = "github:logos-co/logos-cpp-sdk/1dfccf3cdd73cfa18efbe46067899a8f91ec7312";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-view-module-runtime = {
      url = "github:logos-co/logos-view-module-runtime/f19fb2f20f3ac23a0b88d03f2a5e2c63cafb51e6";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-module-client = {
      url = "github:logos-co/logos-module-client/e3669d15d906e3274eb36910f756b70b8f434a73";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-module = {
      url = "github:logos-co/logos-module/194778491ef4dd36967ac40cc2fec6b8a8b1d660";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-liblogos = {
      url = "github:logos-co/logos-liblogos/74d3ce210e8a4c2cd4d9b737f6ca60df95512676";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-module.follows = "logos-module";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package-manager.follows = "logos-package-manager";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.process-stats.follows = "process-stats";
    };
    logos-logoscore-cli = {
      url = "github:logos-co/logos-logoscore-cli/9f56e02b5c4f446f77616b50850854927096a09d";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-module-client.follows = "logos-module-client";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nix-bundle-appimage.follows = "nix-bundle-appimage";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-capability-module = {
      url = "github:logos-co/logos-capability-module/0655be68e0078bede0682bb6a5b53330dac37a72";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-module.follows = "logos-module";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-package = {
      url = "github:logos-co/logos-package/118ccc4efd04eb0c4d541be8db7f1075e014ac39";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-plugin-qt = {
      url = "github:logos-co/logos-plugin-qt/ad384b46c0f08d49a4b8df7ee85329650bab037f";
      inputs.logos-module.follows = "logos-module";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-module-builder = {
      url = "github:logos-co/logos-module-builder/a9360e19634cfd9494e61faec45fd2b7abde8fe4";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-module.follows = "logos-module";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-plugin-core.follows = "logos-plugin-qt";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.logos-standalone-app.follows = "logos-standalone-app";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-bundle-dir = {
      url = "github:logos-co/nix-bundle-dir/4937262f55cf8be942263255dd0801e3e3878bc9";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-bundle-lgx = {
      url = "github:logos-co/nix-bundle-lgx/3c44d99b9d8dbd8a135b44b5b328e6175650305e";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package.follows = "logos-package";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-bundle-appimage = {
      url = "github:logos-co/nix-bundle-appimage/8fcc56b5afcc313ca917cf3487be082ae2f0184c";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-bundle-macos-app = {
      url = "github:logos-co/nix-bundle-macos-app/900aa578506949a1e04d7dfc0b976140a96cbfc9";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-standalone-app = {
      url = "github:logos-co/logos-standalone-app/5e122402898c1d896cc6b72db04c6277697a2f2f";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-design-system.follows = "logos-design-system";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-view-module-runtime.follows = "logos-view-module-runtime";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-basecamp = {
      url = "github:logos-co/logos-basecamp/be3f3a1a69075eb3cbd741651892dc03c993bd26";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-counter.follows = "counter";
      inputs.logos-counter-qml.follows = "counter_qml";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-design-system.follows = "logos-design-system";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-module.follows = "logos-module";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package.follows = "logos-package";
      inputs.logos-package-downloader-module.follows = "logos-package-downloader-module";
      inputs.logos-package-manager.follows = "logos-package-manager";
      inputs.logos-package-manager-module.follows = "logos-package-manager-module";
      inputs.logos-package-manager-ui.follows = "logos-package-manager-ui";
      inputs.logos-view-module-runtime.follows = "logos-view-module-runtime";
      inputs.logos-webview-app.follows = "logos-webview-app";
      inputs.nix-bundle-appimage.follows = "nix-bundle-appimage";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nix-bundle-macos-app.follows = "nix-bundle-macos-app";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-accounts-module = {
      url = "github:logos-co/logos-accounts-module/a419d24945cbed127667a4a2a92770839294decb";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
    };
    logos-accounts-ui = {
      url = "github:logos-co/logos-accounts-ui/e6c3faa6e3ea842a26e071ed555732381b9f51f0";
      inputs.accounts_module.follows = "logos-accounts-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-chat-module = {
      url = "github:logos-co/logos-chat-module/0c7fba90e7aaf462a159ed7357e26ef96a5e3796";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
    };
    logos-chat-ui = {
      url = "github:logos-co/logos-chat-ui/463088afb0dab37f7940a047c45d97fd6e1b0b46";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-chat-module.follows = "logos-chat-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-package-manager = {
      url = "github:logos-co/logos-package-manager/9101875bc103214855bc6217834e22e66802ed86";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-package.follows = "logos-package";
      inputs.nix-bundle-appimage.follows = "nix-bundle-appimage";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-package-downloader = {
      url = "github:logos-co/logos-package-downloader/12a13a37328a8ce64f7e424bc1496c0a27beb098";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nix-bundle-appimage.follows = "nix-bundle-appimage";
      inputs.nix-bundle-dir.follows = "nix-bundle-dir";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-package-manager-module = {
      url = "github:logos-co/logos-package-manager-module/aead48cefdb1f9980c660677f9ffdb1e389271be";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logos-package-manager.follows = "logos-package-manager";
    };
    logos-package-downloader-module = {
      url = "github:logos-co/logos-package-downloader-module/f766852bab46486c31e79ed8a22f363228cd5168";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logos-package-downloader.follows = "logos-package-downloader";
    };
    logos-package-manager-ui = {
      url = "github:logos-co/logos-package-manager-ui/e92efe7132507fd9889e053533b56eb007f26be6";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
      inputs.package_downloader.follows = "logos-package-downloader-module";
      inputs.package_manager.follows = "logos-package-manager-module";
    };
    logos-storage-module = {
      url = "github:logos-co/logos-storage-module/321283bb2de4630084c22b6627e1e846878c7c10";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-storage-ui = {
      url = "github:logos-co/logos-storage-ui/bfa0ae6196d629e6bbf8f028a3fc8ad58f7645dc";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-design-system.follows = "logos-design-system";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-storage-module.follows = "logos-storage-module";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-wallet-module = {
      url = "github:logos-co/logos-wallet-module/6ef4ca0ed8263745c8356570963b5f7ff293e65d";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
    };
    logos-wallet-ui = {
      url = "github:logos-co/logos-wallet-ui/12853f5bec6f20fa7616013ecae9cfd237d56cfe";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
      inputs.wallet_module.follows = "logos-wallet-module";
    };
    logos-blockchain-module = {
      url = "github:logos-blockchain/logos-blockchain-module/08bd849d5a4d331d7c206cdd291105c95147dc12";
      inputs.logos-blockchain.follows = "logos-blockchain";
      inputs.logos-core.follows = "logos-cpp-sdk";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-module-viewer.follows = "logos-module-viewer";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-blockchain-ui = {
      url = "github:logos-blockchain/logos-blockchain-ui/583c309db358555486622fba8eca9c0aac01e7f6";
      inputs.liblogos_blockchain_module.follows = "logos-blockchain-module";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-module.follows = "logos-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logos-package-manager.follows = "logos-package-manager";
      inputs.logos-plugin-qt.follows = "logos-plugin-qt";
      inputs.logos-standalone-app.follows = "logos-standalone-app";
      inputs.logos-view-module-runtime.follows = "logos-view-module-runtime";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.process-stats.follows = "process-stats";
    };
    logos-execution-zone-wallet-ui = {
      url = "github:logos-blockchain/logos-execution-zone-wallet-ui/9e738b54483cc8876a4591330dd67022d68addb3";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-design-system.follows = "logos-design-system";
      inputs.logos-execution-zone-module.follows = "logos-execution-zone-module";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-package-manager.follows = "logos-package-manager";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-execution-zone-module = {
      url = "github:logos-blockchain/logos-execution-zone-module/b94ce296a09ec82cc644d623ef6473ddb729ea58";
      inputs.logos-core.follows = "logos-cpp-sdk";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-module-viewer.follows = "logos-module-viewer";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-libp2p-module = {
      url = "github:logos-co/logos-libp2p-module/49101765f2d29f112744efd3dc45bb6f8e184cb3";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-webview-app = {
      url = "github:logos-co/logos-webview-app/b5d1bb40da6ba550076069a10cf9beaac45aa515";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.nix-bundle-lgx.follows = "nix-bundle-lgx";
    };
    counter_qml.url = "github:logos-co/counter_qml/8029a894f4221f9284efabbedcee7d9d18929777";
    counter = {
      url = "github:logos-co/counter/204ec0d3f0ccffc5d40269db9e7253cba7c330d6";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-design-system = {
      url = "github:logos-co/logos-design-system/75201e56002327864544b729ad0077bca7e5b03d";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-js-sdk = {
      url = "github:logos-co/logos-js-sdk/6b6ccb5f10ea358ae8c9bee4264722dfb0aed76b";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-module.follows = "logos-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logos-module-client.follows = "logos-module-client";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-nim-sdk = {
      url = "github:logos-co/logos-nim-sdk/df1f21906e661d96f5e4bda172cb9a619292b603";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-rust-sdk = {
      url = "github:logos-co/logos-rust-sdk/37840f9f110f5901a7552569853c99e979865b17";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-logoscore-py = {
      url = "github:logos-co/logos-logoscore-py/04048bd5c001b547287cb9d39782e867338b1670";
      inputs.logos-logoscore-cli.follows = "logos-logoscore-cli";
      inputs.logos-nix.follows = "logos-nix";
      inputs.logos-test-modules.follows = "logos-test-modules";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-test-modules = {
      url = "github:logos-co/logos-test-modules/5396c903ea48867ecb0d0c273f604d56b1965a0c";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-logoscore-cli.follows = "logos-logoscore-cli";
      inputs.logos-module-builder.follows = "logos-module-builder";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    process-stats = {
      url = "github:logos-co/process-stats/33ace1270f90c89b3565e803139c0970fcd1ce8f";
      inputs.logos-nix.follows = "logos-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-module-viewer = {
      url = "github:logos-co/logos-module-viewer/b6489c1aab8c1590fa127dbaedb39708f3614fbc";
      inputs.logos-capability-module.follows = "logos-capability-module";
      inputs.logos-cpp-sdk.follows = "logos-cpp-sdk";
      inputs.logos-liblogos.follows = "logos-liblogos";
      inputs.logos-package-manager.follows = "logos-package-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    logos-calc-module = {
      url = "github:logos-co/logos-tutorial?dir=logos-calc-module&rev=707f331f2d8d8825e37856b15ceaabf1cf5e412e";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-calc-ui = {
      url = "github:logos-co/logos-tutorial?dir=logos-calc-ui&rev=707f331f2d8d8825e37856b15ceaabf1cf5e412e";
      inputs.calc_module.follows = "logos-calc-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    logos-calc-ui-cpp = {
      url = "github:logos-co/logos-tutorial?dir=logos-calc-ui-cpp&rev=707f331f2d8d8825e37856b15ceaabf1cf5e412e";
      inputs.calc_module.follows = "logos-calc-module";
      inputs.logos-module-builder.follows = "logos-module-builder";
    };
    # END AUTO-INPUTS
  };

  outputs = { self, nixpkgs, ... }@inputs:
    let
      systems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      forAllSystems = fn: nixpkgs.lib.genAttrs systems fn;

      depGraph = import ./nix/dep-graph.nix;

      # Every logos flake input we iterate over for packages/apps/checks.
      # Excludes `logos-nix` (it's a nixpkgs pin, not a buildable repo).
      repoInputNames = builtins.attrNames
        (builtins.removeAttrs depGraph [ "logos-nix" ]);

      # Mapping from flake input name → submodule directory name under repos/.
      # Only entries where the names differ need to be listed.
      inputToDirOverrides = {
        "logos-calc-module" = "logos-tutorial/logos-calc-module";
        "logos-calc-ui"     = "logos-tutorial/logos-calc-ui";
        "logos-calc-ui-cpp" = "logos-tutorial/logos-calc-ui-cpp";
      };

      inputToDir = name: inputToDirOverrides.${name} or name;

    in {

      # ── Packages ──────────────────────────────────────────────────────────
      # nix build .#logos-cpp-sdk          → default package
      # nix build .#logos-basecamp          → default package
      # nix build .#logos-basecamp--portable → non-default output
      # nix build .#logos-liblogos--portable
      # nix bundle --bundler .#nix-bundle-lgx .#logos-chat-module--lib
      # All repo package outputs are exposed: default as the repo name,
      # non-default as <repo>--<output>.
      packages = forAllSystems (system:
        let
          # Collect all package outputs from all repos.
          # Each repo's packages are forwarded lazily — the value is not
          # evaluated until someone actually builds it, so broken store
          # paths or missing files won't cause errors at evaluation time.
          allPkgs = builtins.foldl' (acc: name:
            let
              repoPkgs = (inputs.${name}.packages.${system} or {});
              outNames = builtins.attrNames repoPkgs;
            in
            acc // builtins.listToAttrs (map (outName:
              let
                attrName = if outName == "default" then name else "${name}--${outName}";
              in
              { name = attrName; value = repoPkgs.${outName}; }
            ) outNames)
          ) {} repoInputNames;
        in allPkgs
      );

      # ── Apps ──────────────────────────────────────────────────────────────
      # nix run .#logos-standalone-app -- --plugin ./result/lib/
      # Forwards apps outputs from all repos. Default app exposed as repo name,
      # non-default as <repo>--<output>.
      apps = forAllSystems (system:
        builtins.foldl' (acc: name:
          let
            repoApps = (inputs.${name}.apps.${system} or {});
            outNames = builtins.attrNames repoApps;
          in
          acc // builtins.listToAttrs (map (outName:
            let
              attrName = if outName == "default" then name else "${name}--${outName}";
            in
            { name = attrName; value = repoApps.${outName}; }
          ) outNames)
        ) {} repoInputNames
      );

      # ── Dev Shells ────────────────────────────────────────────────────────
      # nix develop          → workspace shell (ws CLI + common tools)
      # nix develop .#logos-cpp-sdk → that repo's own devShell
      # nix develop          → workspace shell with ws CLI + common tools
      # For sub-repo devShells use: nix develop path:./repos/<repo-name>
      #   or: ws develop <repo-name>
      devShells = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; };
          # Always delegates to the live scripts/ws in the workspace,
          # without needing to rebuild the devshell. Falls back to the
          # flake directory if LOGOS_WORKSPACE_ROOT is not set.
          wsScript = pkgs.writeShellScriptBin "ws" ''
            exec "''${LOGOS_WORKSPACE_ROOT:-${builtins.toString ./.}}/scripts/ws" "$@"
          '';
        in {
          default = import ./nix/devshell.nix { inherit pkgs wsScript; };
        }
      );

      # ── Checks ────────────────────────────────────────────────────────────
      # nix flake check        → run ALL repo checks
      # nix build .#checks.x86_64-linux.logos-cpp-sdk--test
      checks = forAllSystems (system:
        builtins.foldl' (acc: name:
          let
            result = builtins.tryEval (inputs.${name}.checks.${system} or {});
            repoChecks = if result.success then result.value else {};
            prefixed = nixpkgs.lib.mapAttrs'
              (cname: drv: { name = "${name}--${cname}"; value = drv; })
              repoChecks;
          in
          acc // prefixed
        ) {} repoInputNames
      );

      # ── Bundlers ──────────────────────────────────────────────────────────
      # Forwards nix-bundle-lgx bundlers so scripts can use "$WORKSPACE_ROOT"
      # as the --bundler reference.
      bundlers = forAllSystems (system:
        inputs.nix-bundle-lgx.bundlers.${system}
      );

      # ── Lib (for programmatic use) ────────────────────────────────────────
      lib = {
        inherit repoInputNames inputToDir;
        # Dependency graph: input name → { deps, follows, hasTests }
        depGraph = depGraph;
      };
    };
}
